### ISSUE TITLE
Doesn't work with Python 2.6

### ISSUE THREAD

**Issue by rassie** [mgedmin/check-manifest#22]
According to [docs](http://docs.python.org/2/library/tarfile.html), `TarFile` only supports context manager protocol since 2.7, so that on 2.6 `check-manifest` crashes with `AttributeError: 'TarFile' object has no attribute '__exit__'`
